baseURL: https://andrewromans.com
languageCode: en-us
title: Andrew Romans
theme: simple

params:
  status: Just placed top 100 in Flare-On 12! It is an amazing competition, with amazing RE challenges! Follow the link if your interested - https://flare-on12.ctfd.io/ 
  status_p2: Come back after October 24th for my writeups on all 9!
  timeline: 
    current: "CS6265: InfoSec Lab (Binary Exploitation)"
    next_1: PNPT Certification Study/Training
    next_2: Writeups Writing
  links:
    Home:   /
    Posts:  /posts
    Resume: /resume
    Tags:   /tags

  contacts:
    email: andrew.romans@hotmail.com
    github: aromans
    linkedin: andrew-romans

  social:
    github:   https://github.com/aromans
    linkedin: https://www.linkedin.com/in/andrew-romans/

  profile:
    firstname: Andrew
    lastname: Romans
    location: Carlsbad, CA
    bio: Security Engineer and Vulnerability Researcher specializing in Reverse Engineering and Malware Analysis, with nearly 3 years of professional experience in cybersecurity. Day-to-day expertise includes advanced malware analysis, penetration testing, and vulnerability research across diverse systems and architectures. Proficient in low-level languages including C, x86, arm, and mips, with continued passion for competitive CTFs and staying current with emerging threats and exploitation techniques.
  about: Welcome! This website hosts everything from my CV/Contact Information to CTF challenge writeups, Malware Analysis, and more.  💻👋
