baseURL: https://andrewromans.com
languageCode: en-us
title: Andrew Romans
theme: simple

params:
  status: I finished my RE and Binary Exploitation class at GaTech in 6th place; my next class in my Masters will be in Network Security. Additionally, I have some new opportunities coming around the horizon that I am very much excited for, but will need to remain a secret... for now! 
  status_p2: In the meantime, I was able to finally finish Task 9 in the NSA Codebreaker Challenge which makes me a Solver! If you are interested in my writeups, they should be available for reading below. Currently, I am participating in Kringlecon 2022, TryHackMe's Advent of Cyber 4, and studying for Cysa+ and PNPT.
  timeline: 
    current: "CS6265: InfoSec Lab (Binary Exploitation)"
    next_1: PNPT Certification Study/Training
    next_2: Writeups Writing
  links:
    Home:   /
    Posts:  /posts
    Resume: /resume
    Tags:   /tags

  contacts:
    email: andrew.romans@hotmail.com
    github: aromans
    linkedin: andrew-romans

  social:
    github:   https://github.com/aromans
    linkedin: https://www.linkedin.com/in/andrew-romans/

  profile:
    firstname: Andrew
    lastname: Romans
    location: Warner Robins, GA
    bio: Experienced Software Engineer with a passion and focus in Cybersecurity, transitioning from a Machine Learning and Simulation background. Proficient in many languages, from C and x86 assembly to Python. Spends free time participating in CTFs, pwning challenges in TryHackMe and HackTheBox, and staying up‑to‑date with techniques on malware analysis, reverse engineering, and recent cyber threats.
  about: I am an experienced software engineer with a passion and focus in Cybersecurity. I am currently working towards a M.S. in Cybersecurity online at Georgia Tech. I have previous work experience in Machine Learning and Simulation Development focused around Natural Language Processing and Nursing Education, and looking to transition to a role in Cybersecurity. This website hosts everything from my CV/Contact Information to CTF challenge writeups, Malware Analysis, School-Work Writeups, and more.  💻👋
