baseURL: https://andrewromans.com
languageCode: en-us
title: Andrew Romans
theme: simple

params:
  status: I am currently Reverse Engineering and Exploiting Binaries in the CS6265:InfoSecLab class at GaTech. This course covers reverse engineering, exploitation, binary analysis, and web topics while providing 11 to 12 challenges in a CTF format every week for the whole semester. 

  status_p2: On the side, I have finished 8/9 of the NSA Codebreaker Challenges and am slowly juggling Task 9 while working on the class challenges. Once this class is complete, I will be able to catch up on writing my baclog WriteUps and training for the PNPT Certification.
  timeline: 
    current: "CS6265: InfoSec Lab (Binary Exploitation)"
    next_1: PNPT Certification Study/Training
    next_2: Writeups Writing
  links:
    Home:   /
    Posts:  /posts
    Resume: /resume
    Tags:   /tags

  contacts:
    email: andrew.romans@hotmail.com
    github: aromans
    linkedin: andrew-romans

  social:
    github:   https://github.com/aromans
    linkedin: https://www.linkedin.com/in/andrew-romans/

  profile:
    firstname: Andrew
    lastname: Romans
    location: Warner Robins, GA
    bio: Experienced Software Engineer with a passion and focus in Cybersecurity, transitioning from a Machine Learning and Simulation background. Proficient in many languages, from C and x86 assembly to Python. Spends free time participating in CTFs, pwning challenges in TryHackMe and HackTheBox, and staying up‑to‑date with techniques on malware analysis, reverse engineering, and recent cyber threats.
  about: I am an experienced software engineer with a passion and focus in Cybersecurity. I am currently working towards a M.S. in Cybersecurity online at Georgia Tech. I have previous work experience in Machine Learning and Simulation Development focused around Natural Language Processing and Nursing Education, and looking to transition to a role in Cybersecurity. This website hosts everything from my CV/Contact Information to CTF challenge writeups, Malware Analysis, School-Work Writeups, and more.  💻👋
