baseURL: https://andrewromans.com
languageCode: en-us
title: Andrew Romans
theme: simple

params:
  links:
    Home:   /
    Posts:  /posts
    Resume: /resume
    Tags:   /tags

  contacts:
    email: andrew.romans@hotmail.com
    github: aromans
    linkedin: andrew-romans

  social:
    github:   https://github.com/aromans
    linkedin: https://www.linkedin.com/in/andrew-romans/

  profile:
    firstname: Andrew
    lastname: Romans
    location: Warner Robins, GA
    bio: Experienced Software Engineer with a passion and focus in Cybersecurity, transitioning from a Machine Learning and Simulation background. Proficient in many languages, from C and x86 assembly to Python. Spends free time participating in CTFs, pwning challenges in TryHackMe and HackTheBox, and staying up‑to‑date with techniques on malware analysis, reverse engineering, and recent cyber threats.
  about: I am a software engineer with experience in many programming languages with a passion and a focus in Cybersecurity. I am currently working towards a M.S. in Cybersecurity online at Georgia Tech. I have previous work experience in Machine Learning and Simulation Development focused around Natural Language Processing and Nursing Education. This website hosts everything from my CV/Contact Information to my CTF challenge writeups, Malware Analysis, School-Work Writeups, and more.  💻👋
